<#
.SYNOPSIS
    __ZSC_DISPLAY_NAME__ - deployment script generated by ZeroStress Cockpit.

.DESCRIPTION
    Wrapper for PSAppDeployToolkit v4. Install and uninstall logic and the
    detection marker come from one package manifest. Do not edit by hand;
    rebuild the package in the Cockpit instead.

    Package identifier: __ZSC_IDENTIFIER__
    Detection marker:   __ZSC_MARKER_PLAIN__ (Installed = Y)

.PARAMETER DeploymentType
    Install, Uninstall or Repair.

.PARAMETER DeployMode
    Auto, Interactive, NonInteractive or Silent.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [ValidateSet('Install', 'Uninstall', 'Repair')]
    [System.String]$DeploymentType = 'Install',

    [Parameter(Mandatory = $false)]
    [ValidateSet('Auto', 'Interactive', 'NonInteractive', 'Silent')]
    [System.String]$DeployMode = 'Interactive',

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$AllowRebootPassThru,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$TerminalServerMode,

    [Parameter(Mandatory = $false)]
    [System.Management.Automation.SwitchParameter]$DisableLogging
)

$adtSession = @{
    AppVendor = __ZSC_VENDOR__
    AppName = __ZSC_NAME__
    AppVersion = __ZSC_VERSION__
    AppArch = __ZSC_ARCH__
    AppLang = __ZSC_LANG__
    AppRevision = __ZSC_REVISION__
    AppScriptVersion = '1.0.0'
    AppScriptDate = __ZSC_DATE__
    AppScriptAuthor = 'ZeroStress Cockpit'
    InstallName = ''
    InstallTitle = ''
    DeployAppScriptFriendlyName = $MyInvocation.MyCommand.Name
    DeployAppScriptVersion = '4.0.0'
    DeployAppScriptParameters = $PSBoundParameters
}

$zscMarkerKey = __ZSC_MARKER_KEY__
$zscIdentifier = __ZSC_PACKAGE_ID_LITERAL__
$zscInstallerFile = __ZSC_INSTALLER_FILE__

function Install-ADTDeployment
{
    [CmdletBinding()]
    param()

    $adtSession.InstallPhase = "Pre-$($DeploymentType)"

__ZSC_CLOSE_PROCESSES__

    $adtSession.InstallPhase = $DeploymentType

    $installerPath = Join-Path -Path $adtSession.DirFiles -ChildPath $zscInstallerFile
    if (-not (Test-Path -LiteralPath $installerPath -PathType Leaf))
    {
        throw "Installer not found in package: $installerPath"
    }
__ZSC_INSTALL_BLOCK__

    $adtSession.InstallPhase = "Post-$($DeploymentType)"

    # Detection marker: Intune checks Installed = Y and DisplayVersion under this key
    Set-ADTRegistryKey -Key $zscMarkerKey -Name 'Installed' -Value 'Y' -Type 'String'
    Set-ADTRegistryKey -Key $zscMarkerKey -Name 'DisplayVersion' -Value $adtSession.AppVersion -Type 'String'
    Set-ADTRegistryKey -Key $zscMarkerKey -Name 'PackageIdentifier' -Value $zscIdentifier -Type 'String'
    Set-ADTRegistryKey -Key $zscMarkerKey -Name 'InstalledOn' -Value (Get-Date -Format 'yyyy-MM-dd HH:mm:ss') -Type 'String'
}

function Uninstall-ADTDeployment
{
    [CmdletBinding()]
    param()

    $adtSession.InstallPhase = "Pre-$($DeploymentType)"

__ZSC_CLOSE_PROCESSES__

    $adtSession.InstallPhase = $DeploymentType

    $installerPath = Join-Path -Path $adtSession.DirFiles -ChildPath $zscInstallerFile
__ZSC_UNINSTALL_BLOCK__

    $adtSession.InstallPhase = "Post-$($DeploymentType)"

    # Marker removal makes Intune report the app as not installed
    Remove-ADTRegistryKey -Key $zscMarkerKey -Recurse
}

function Repair-ADTDeployment
{
    [CmdletBinding()]
    param()

    # Repair is install over the top; the marker is rewritten by Install
    Install-ADTDeployment
}

# Toolkit bootstrap: module from the package folder, otherwise an installed module
try
{
    $moduleManifest = Join-Path -Path $PSScriptRoot -ChildPath 'PSAppDeployToolkit\PSAppDeployToolkit.psd1'
    if (Test-Path -LiteralPath $moduleManifest -PathType Leaf)
    {
        Get-ChildItem -LiteralPath (Join-Path -Path $PSScriptRoot -ChildPath 'PSAppDeployToolkit') -Recurse -File | Unblock-File -ErrorAction SilentlyContinue
        Import-Module -Name $moduleManifest -Force
    }
    else
    {
        Import-Module -Name 'PSAppDeployToolkit' -MinimumVersion '4.0.0' -Force
    }
    $adtSession = Open-ADTSession -SessionState $ExecutionContext.SessionState @adtSession -DeploymentType $DeploymentType -DeployMode $DeployMode -AllowRebootPassThru:$AllowRebootPassThru -TerminalServerMode:$TerminalServerMode -DisableLogging:$DisableLogging -PassThru
}
catch
{
    $Host.UI.WriteErrorLine(($_ | Out-String))
    exit 60008
}

try
{
    & "$($DeploymentType)-ADTDeployment"
    Close-ADTSession
}
catch
{
    Write-ADTLogEntry -Message ("Deployment failed: " + ($_ | Out-String)) -Severity 3
    Close-ADTSession -ExitCode 60001
}
